version: "3.8"

services:
  the_game:
    container_name: the-game
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - PROJECT_DIR=${PROJECT_DIR}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PLAYERS_DB=${POSTGRES_PLAYERS_DB}
    links:
      - players_database
    volumes:
      - ./src/:${PROJECT_DIR}/src/
      - ./game_data/:${PROJECT_DIR}/game_data/
      - ./logs/:${PROJECT_DIR}/logs/

  players_database:
    container_name: players-database
    image: postgres:latest
    volumes:
      - ./players_database/:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_PLAYERS_DB}
